---
  - name: "Create EKS Cluster for {{ project_tag }}"
    hosts: localhost
    connection: local 
    tasks:

   # Docs that may be of future help
    # https://github.com/awsdocs/amazon-eks-user-guide/tree/master/doc_source

    # https://docs.ansible.com/ansible/latest/collections/community/aws/eks_cluster_module.html#ansible-collections-community-aws-eks-cluster-module
    # I am not using the community.aws module for eks, I don't think it exposes enough options for what I need
    # Opting to go with the approach of using `eksctl` as show in below:
    #  - https://github.com/aws-samples/aws-amazon-eks-ansible-example/blob/main/eks-deploy-cluster.playbook.yaml

    - name: check if eks cluster setup exists for '{{ eks_clustername }}' in '{{ region_name }}'
      shell: eksctl get cluster {{ eks_clustername }} --region {{ region_name }} --verbose 0
      register: eks_check_output
      ignore_errors: true

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: eks_check_output
      when: ansible_verbosity > 0

    - name: create the eks cluster
      shell: >
        eksctl  create cluster \
        --name {{ eks_clustername }} \
        --version {{ eks_clusterversion }} \
        --region {{ region_name }} \
        --node-type {{ eks_worker_instancetype }} \
        --nodes-min {{ eks_worker_mincount }} \
        --nodes-max {{ eks_worker_maxcount }} \
        --managed
      when: eks_check_output.rc != 0

    - name: write the kube config "./{{ eks_clustername }}.{{ region_name }}.kubeconfig"
      shell: >
        eksctl utils write-kubeconfig \
        --cluster {{ eks_clustername }} \
        --region {{ region_name }} \
        --kubeconfig="./{{ eks_clustername }}.{{ region_name }}.kubeconfig"

    # See https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html for enabling oidc-provider in EKS
    # 
    # Example:
    # aws iam list-open-id-connect-providers | grep $oidc_id | cut -d "/" -f4
    # oidc_id=$(aws eks describe-cluster --name eks-jwm-tmp-hacking --region us-east-1 --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5)
    # eksctl utils associate-iam-oidc-provider --cluster eks-jwm-tmp-hacking --region us-east-1 --approve

    - name: get "cluster.identity.oidc.issuer" for {{ eks_clustername }} in {{ region_name }} 
      shell: aws eks describe-cluster --name {{ eks_clustername }} --region {{ region_name }} --query "cluster.identity.oidc.issuer" --output text | cut -d '/' -f 5 
      register: eks_identity_oidc_issuer
      ignore_errors: true

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: eks_identity_oidc_issuer
      when: ansible_verbosity > 0

    - name: list open-id-connect-provider for {{ eks_clustername }} in {{ region_name }} 
      shell: aws iam list-open-id-connect-providers | grep {{ eks_identity_oidc_issuer.stdout }} | cut -d "/" -f4
      register: eks_oidc_provider
      ignore_errors: true

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: eks_oidc_provider
      when: ansible_verbosity > 0
 
    - name: add the oidc provider for iam
      shell: >
        eksctl  utils associate-iam-oidc-provider \
        --cluster {{ eks_clustername }} \
        --region {{ region_name }} \
        --approve
      when: eks_oidc_provider.stdout == ""

    - name: enable cloudwatch logging
      shell: >
        eksctl  utils update-cluster-logging \
        --cluster {{ eks_clustername }} \
        --enable-types all \
        --approve \
        --region {{ region_name }}

    # EBSCSI Driver setup
    # https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
    # https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html
    # https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html

    - name: check if aws-ebs-csi-driver addon is installed in {{ eks_clustername }} in {{ region_name }} 
      shell: eksctl get addon --name aws-ebs-csi-driver --cluster {{ eks_clustername }} --region {{ region_name }}
      register: check_eks_ebs_csi_addon
      ignore_errors: true

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: check_eks_ebs_csi_addon
      when: ansible_verbosity > 0

    - name: create an IAM Role for the EBS CSI Driver '{{ eks_ebs_csi_iam_role_name }}'
      shell: >
        eksctl create iamserviceaccount \
        --name ebs-csi-controller-sa \
        --namespace kube-system \
        --cluster {{ eks_clustername }} \
        --region {{ region_name }} \
        --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
        --approve \
        --role-only \
        --role-name {{ eks_ebs_csi_iam_role_name }}
      register: eks_ebs_csi_iam_role
      when: check_eks_ebs_csi_addon.rc != 0

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: eks_ebs_csi_iam_role
      when: ansible_verbosity > 0

    - name: get the ARN of the IAM Role for the EBS CSI Driver '{{ eks_ebs_csi_iam_role_name }}'
      shell: >
        eksctl get iamserviceaccount \
        --name ebs-csi-controller-sa \
        --cluster {{ eks_clustername }} \
        --region {{ region_name }} \
        --output json | jq -r '.[0].status.roleARN' 
      register: eks_ebs_csi_iam_role_arn
      when: check_eks_ebs_csi_addon.rc != 0

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: eks_ebs_csi_iam_role_arn
      when: ansible_verbosity > 0

    - name: install ebs csi addon to {{ eks_clustername }} in {{ region_name }} with {{ eks_ebs_csi_iam_role_arn }}
      shell: >
        eksctl create addon --name aws-ebs-csi-driver \
        --cluster {{ eks_clustername }} --region {{ region_name }} \
        --service-account-role-arn {{ eks_ebs_csi_iam_role_arn.stdout }} \
        --force
      when: check_eks_ebs_csi_addon.rc != 0

